name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm install
      - name: Build
        run: npm run build-npm
      - name: Publish
        run: npm publish
  publish_jsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Publish package
        run: npx jsr publish
