name: Publish to NPM

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish
